name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer & Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --user --upgrade Cython==0.29.33 buildozer

      - name: Force SDK License Acceptance
        run: |
          # මෙතනින් අපි Android SDK එක ඉන්ස්ටෝල් වෙන්න කලින්ම Licenses වලට අවසර දෙනවා
          mkdir -p $HOME/.android
          touch $HOME/.android/repositories.cfg
          export PATH=$PATH:$HOME/.local/bin
          # Buildozer ට කියනවා SDK එක ලෑස්ති කරන්න කියලා
          yes | buildozer android p4a -- help

      - name: Run Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # පියවරෙන් පියවර log බලමු
          buildozer android debug
        continue-on-error: false

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
